default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: michigan_prototype_development
test:
  <<: *default
  database: michigan_prototype_test

staging:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
